"""Generate the dev dashboard from the entity registry.

Entity IDs depend on the HA language and areas (e.g. "kuchyne_…"), so the
dashboard is built from the unique IDs of FVE Optimizer entities.

    docker exec -i fve-optimizer-dev python3 - < make_dashboard.py

Then reload the browser (the dashboard is in YAML mode, no restart needed
after the first one).
"""

import json
from pathlib import Path

import yaml

CONFIG = Path("/config")
registry = json.loads((CONFIG / ".storage/core.entity_registry").read_text())["data"]["entities"]
entries = json.loads((CONFIG / ".storage/core.config_entries").read_text())["data"]["entries"]

entry = next(e for e in entries if e["domain"] == "fve_optimizer")
entry_id = entry["entry_id"]
subentries = {s["subentry_id"]: s for s in entry.get("subentries", [])}

by_uid = {
    e["unique_id"]: e["entity_id"]
    for e in registry
    if e["platform"] == "fve_optimizer" and e["config_entry_id"] == entry_id
}


def hub(key: str) -> str | None:
    return by_uid.get(f"{entry_id}_{key}")


def dev(subentry_id: str, key: str) -> str | None:
    return by_uid.get(f"{entry_id}_{subentry_id}_{key}")


def only(*ids):
    return [i for i in ids if i]


def entities_card(title, ids):
    ids = only(*ids)
    return {"type": "entities", "title": title, "entities": ids} if ids else None


subs = list(subentries)
reason = [dev(sid, "reason") for sid in subs]
allocated = [dev(sid, "allocated") for sid in subs]


def card(c):
    return c if c and c.get("entities", True) else None


def view(title, path, cards):
    return {"title": title, "path": path, "type": "masonry", "cards": [c for c in cards if c]}


status = hub("status")

# Dev only: the simulator next to the optimizer's reaction. History, statistics
# and settings live in the integration's own "FVE Optimizer" panel.
simulator = {
    "type": "entities",
    "title": "Simulátor",
    "entities": [
        {"type": "section", "label": "Výroba a spotřeba"},
        "input_number.sim_pv_available",
        "input_number.sim_house_load",
        "input_number.sim_forecast_remaining",
        {"type": "section", "label": "Stav"},
        "input_number.sim_battery_soc",
        "input_number.sim_water_temp",
        "input_number.sim_ev_soc",
        "input_boolean.sim_ev_connected",
        "input_boolean.sim_hdo",
        {"type": "section", "label": "Čas"},
        "input_number.sim_speed",
    ],
}
control = entities_card("Řízení", [hub("enabled"), hub("dry_run")] + [dev(sid, "control") for sid in subs])

dashboard = {
    "title": "Simulátor",
    "views": [
        {
            "title": "Simulátor",
            "path": "simulator",
            "type": "sections",
            "max_columns": 3,
            "sections": [
                {"type": "grid", "cards": [simulator]},
                {"type": "grid", "cards": [c for c in (
                    {"type": "custom:fve-optimizer-card", "entity": status,
                     "sections": ["summary", "devices"]} if status else None,
                ) if c]},
                {"type": "grid", "cards": [c for c in (
                    control,
                    {"type": "custom:fve-optimizer-card", "entity": status, "sections": ["log"]}
                    if status else None,
                ) if c]},
            ],
        }
    ],
}

out = CONFIG / "dashboards/fve.yaml"
out.parent.mkdir(exist_ok=True)
out.write_text(
    "# Generated by dev/make_dashboard.py – do not edit, regenerate instead.\n"
    + yaml.safe_dump(dashboard, allow_unicode=True, sort_keys=False)
)
print(f"Written {out}")
